[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  mainBranch = 'main'
  branches = ['main']
  customDomain = "awesome-exp.dev"
  renderJavaScript = true
  template = "hierarchical"
