version: 2.1

jobs:
  index:
    docker:
      - image: algolia/docsearch-scraper
    steps:
      - checkout
      - run: sudo apt-get install jq -y
      - run:
          name: Run crawler
          command: |
                export CONFIG=$(cat ./search_configs/site.json | jq -r tostring) 
                cd ../ 
                pipenv run python -m src.index

workflows:
  index-algolia:
    jobs:
      - index:
          filters:
            branches:
              only:
                - main
                - circleci-project-setup
