version: 2.1

jobs:
  index:
    docker:
      - image: algolia/docsearch-scraper
    steps:
      - checkout
      - run: sudo apt-get install jq -y
      - run:
          name: Run crawler
          command: |
                export CONFIG=$(cat ./search_configs/site.json | jq -r tostring) 
                cd ../ 
                pipenv run python -m src.index

workflows:
  index-schedule:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
             only:
                - main
    jobs:
      - index
  index-tagged:
    jobs:
      - index:
          filters:
            tags:
              only: /^index.*/
            branches:
              ignore: /.*/
